---
- name: Create multiple users and set sudo password
  hosts: all
  become: yes
  vars_prompt:
    - name: "user1_name"
      prompt: "Masukkan nama pengguna pertama (harry)"
      private: no
    - name: "user1_password"
      prompt: "Masukkan password untuk pengguna pertama (harry)"
      private: yes
    - name: "user2_name"
      prompt: "Masukkan nama pengguna kedua (natasha)"
      private: no
    - name: "user2_password"
      prompt: "Masukkan password untuk pengguna kedua (natasha)"
      private: yes
    - name: "user3_name"
      prompt: "Masukkan nama pengguna ketiga (sarah)"
      private: no
    - name: "user3_password"
      prompt: "Masukkan password untuk pengguna ketiga (sarah)"
      private: yes

  vars:
    ansible_become_pass: "{{ sudo_password }}"

  tasks:
    - name: Ensure users are present
      ansible.builtin.user:
        name: "{{ item.name }}"
        password: "{{ item.password | password_hash('sha512') }}"
        state: present
        shell: /bin/bash
      loop:
        - { name: "{{ user1_name }}", password: "{{ user1_password }}" }
        - { name: "{{ user2_name }}", password: "{{ user2_password }}" }
        - { name: "{{ user3_name }}", password: "{{ user3_password }}" }

    - name: Update sudo password
      ansible.builtin.command: "echo 'root:{{ sudo_password }}' | chpasswd"
      args:
        sheel: /bin/bash
