---
- name: Deploy Web App otomatis
  hosts: RHEL9-for-automate-deployment
  become: yes
  vars:
    app_repo: "https://github.com/RaihanEfelMaulana/web-apps.git"
    app_dest: "/var/www/html"
    app_port: 80
    app_url: "http://{{ ansible_host }}"

  tasks:
    - name: Pastikan Apache HTTPD terinstall
      yum:
        name: httpd
        state: present

    - name: Pastikan git terinstall
      yum:
        name: git
        state: present

    - name: Pastikan firewalld sudah terinstall
      yum:
        name: firewalld
        state: present

    - name: Pastikan firewalld aktif dan berjalan
      service:
        name: firewalld
        state: started
        enabled: yes

    - name: Izinkan HTTP & HTTPS di firewall
      firewalld:
        service: "{{ item }}"
        permanent: yes
        state: enabled
      loop:
        - http
        - https

    - name: Reload firewall untuk menerapkan perubahan
      command: firewall-cmd --reload

    - name: Start dan enable httpd
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Tandai /var/www/html sebagai safe directory untuk Git
      command: git config --global --add safe.directory /var/www/html

    - name: Clone atau update repo web-app
      git:
        repo: "{{ app_repo }}"
        dest: "{{ app_dest }}"
        version: main
        force: yes

    - name: Set ownership dan permission
      file:
        path: "{{ app_dest }}"
        owner: apache
        group: apache
        mode: '0755'
        recurse: yes

    - name: Restart Apache setelah update
      service:
        name: httpd
        state: restarted

    - name: Tampilkan URL aplikasi
      debug:
        msg: "Web App berhasil dideploy 🚀. Akses di {{ app_url }}"
