- name: Create a folder named 'test' on a Windows host
  hosts: windows
  tasks:
    - name: Create folder 'test' in C:\
      ansible.windows.win_file:
        path: C:\test
        state: directory
