---
- name: Update all packages on RHEL servers
  hosts: all
  become: yes
  vars_prompt:
    - name: "sudo_password"
      prompt: "Masukkan password sudo"
      private: yes
  vars:
    ansible_become_pass: "{{ sudo_password }}"
  tasks:
    - name: Update all packages
      ansible.builtin.yum:
        name: "*"
        state: latest
