---
- name: Create local machine users
  hosts: windowsgroup
  gather_facts: no

  vars_files:
    - pass.yml ## Vault file

  tasks:
    - name: Create TMM group
      ansible.windows.win_group:
        name: TMM
        state: present

    - name: Create DevOps users
      ansible.windows.win_user:
        name: "{{ item }}"
        password: "{{ tmm_password }}"
        groups: TMM
        state: present
      loop:
       - user1
       - user2
       - user3
