---
- name: Reset Password User di Windows
  hosts: windows
  gather_facts: no
  tasks:
    - name: Reset Password User
      ansible.windows.win_user:
        name: "{{ username }}"
        password: "{{ new_password }}"
        state: present
      register: result

    - name: Result 
      debug:
        msg: "Password untuk user {{ username }} telah diubah!"
