---
- hosts: windowsgroup
  gather_facts: false
  collections:
   - ansible.windows

  vars_prompt:
    - name: username
      prompt: "Enter the username to reset the password for"
      private: no

    - name: user_password
      prompt: "Enter the new password"
      private: yes

  tasks:
   ## Add tasks below
    - name: Reset local user password
      ansible.windows.win_user:
        name: "{{ username }}"
        password: "{{ user_password }}"
