---
- name: Add User Windows Based on Division
  hosts: windowsgroup
  gather_facts: no
  tasks:
    - name: Create division-based groups
      ansible.windows.win_group:
        name: "{{ item }}"
        state: present
      loop:
        - Marketing
        - Product
        - HR

    - name: Add new users
      no_log: true  
      ansible.windows.win_user:
        name: "{{ item.name }}"
        password: "{{ item.password }}"
        state: present
      loop:
        - { name: 'alice', password: '{{ user_password }}', division: 'Marketing' }
        - { name: 'bob', password: '{{ user_password }}', division: 'Product' }
        - { name: 'charlie', password: '{{ user_password }}', division: 'HR' }

    - name: Assign users to their respective groups
      ansible.windows.win_group_membership:
        name: "{{ item.division }}"
        members:
          - "{{ item.name }}"
        state: present
      loop:
        - { name: 'alice', division: 'Marketing' }
        - { name: 'bob', division: 'Product' }
        - { name: 'charlie', division: 'HR' }
