---
- hosts: windowsgroup
  gather_facts: false
  collections:
    - ansible.windows

  tasks:
    - name: Reset password for user1
      ansible.windows.win_user:
        name: "user1"
        password: "trootent"
