---
- name: Provision System Software
  hosts: windowsgroup
  gather_facts: false

  tasks:
  ## Add tasks or uncomment the below
  - name: Install required software
    chocolatey.chocolatey.win_chocolatey:
      name:
      - podman-desktop
      state: present
