---
- name: Add User Windows
  hosts: windowsgroup
  gather_facts: no
  tasks:
    - name: Add new user
      ansible.windows.win_user:
        name: "johndoe"   # Nama user tetap
        password: "{{ user_password }}"  # Password dari Survey
        state: present
