---
- name: Create local users on Windows
  hosts: windowsgroup
  become: yes
  vars_files:
    - secrets.yml
  tasks:
    - name: Create user with encrypted password
      ansible.builtin.user:
        name: johndoe
        password: "{{ user_password }}"
