---
- name: Add User Windows
  hosts: windowsgroup
  gather_facts: no
  tasks:
    - name: Add new users
      ansible.windows.win_user:
        name: "{{ item }}"  
        password: "{{ user_password }}"  
        state: present
      loop:
        - johndoe
        - raihan   
        - user123 


#---
#- name: Add User Windows
#  hosts: windowsgroup
#  gather_facts: no
#  tasks:
#    - name: Add new user
#      ansible.windows.win_user:
#        name: "johndoe" 
#        password: "{{ user_password }}" 
#        state: present
