---
- name: Delete User Windows
  hosts: windowsgroup
  gather_facts: no
  tasks:
    - name: Delete user from Windows
      ansible.windows.win_user:
        name: "{{ user_name }}"  
        password: "{{ user_password }}" 
        state: absent
