---
- name: Delete Multiple Users Windows
  hosts: windowsgroup
  gather_facts: no
  tasks:
    - name: Delete multiple users
      ansible.windows.win_user:
        name: "{{ item }}"
        state: absent
      loop: "{{ user_list.splitlines() }}"
