---
- name: Create local users on Windows
  hosts: windowsgroup
  vars_files:
    - /root/secrets.yml
  tasks:
    - name: Create user with encrypted password
      ansible.windows.win_user:
        name: johndoe
        password: "{{ user_password }}"

