---
- name: Reset Password User di Windows
  hosts: windows
  gather_facts: no
  tasks:
    - name: Reset password user johndoe
      ansible.windows.win_user:
        name: johndoe
        password: NewP@ssw0rd!
        update_password: always

#---
#- hosts: windowsgroup
#  gather_facts: false
#  collections:
#    - ansible.windows

#  vars_prompt:
#    - name: username
#      prompt: "Enter the username to reset the password for"
#      private: no  # Menonaktifkan input tersembunyi untuk username
#    - name: user_password
#      prompt: "Enter the new password"
#      private: yes  # Mengaktifkan input tersembunyi untuk password

#  tasks:
#    - name: Reset password for specified user
#      ansible.windows.win_user:
#        name: "{{ username }}"
#        password: "{{ user_password }}"
