- name: Reset Password Windows
  hosts: windows
  tasks:
    - name: Reset password user Windows
      win_user:
        name: "{{ username }}"
        password: "{{ new_password }}"
        state: present
